version: 0.0
os: linux

files:
  -source: files/nginx.conf
  destination: /etc/nginx/
  -source: files/staticserver.js
  destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    -source: scripts/BeforeInstall.sh
  AfterInstall:
    -source: scripts/AfterInstall.sh
