version: 0.0

containers:
  main:
    phases:
      install:
        commands:
          - echo Entering install phase...
      pre_build:
        commands:
          - echo Entering pre_build phase...
      during_build:
        commands:
          - echo Entering during_build phase...
      post_build:
        commands:
          - echo Entering post_build phase...
    artifacts:
       type: zip
       files:
         - 'target/appspec.yml'
         - 'target/files/'
         - 'target/scripts/'
